export enum EnvKey {
  DB_URI = 'DB_URI',
  GOOGLE_SERVICE_ACCOUNT = 'GOOGLE_SERVICE_ACCOUNT',
  PORT = 'PORT',
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  ACCESS_TOKEN_EXP = 'ACCESS_TOKEN_EXP',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  REFRESH_TOKEN_EXP = 'REFRESH_TOKEN_EXP',
  COIN_API_BASE_URL = 'COIN_API_BASE_URL',
  COIN_API_KEY = 'COIN_API_KEY',
}
