export enum EnvKey {
  DB_URI = 'DB_URI',
  SOCIAL_LOGIN_JSON_PATH = 'SOCIAL_LOGIN_JSON_PATH',
  PORT = 'PORT',
  EMAIL_USER = 'EMAIL_USER',
  EMAIL_API_KEY = 'EMAIL_API_KEY',
  EMAIL_SERVICE = 'EMAIL_SERVICE',
  EMAIL_FROM = 'EMAIL_FROM',
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  ACCESS_TOKEN_EXP = 'ACCESS_TOKEN_EXP',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  REFRESH_TOKEN_EXP = 'REFRESH_TOKEN_EXP',
}
