name: app-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME}}
          heroku_email: ${{secrets.ACCOUNT_EMAIL}}
          usedocker: true
        env:
          HD_NODE_ENV: production
          HD_DB_URI: ${{ secrets.DB_URI }}
          HD_ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
          HD_ACCESS_TOKEN_EXP: ${{secrets.ACCESS_TOKEN_EXP}}
          HD_REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
          HD_REFRESH_TOKEN_EXP: ${{secrets.REFRESH_TOKEN_EXP}}
          HD_GOOGLE_SERVICE_ACCOUNT: ${{secrets.GOOGLE_SERVICE_ACCOUNT}}
          HD_COIN_API_BASE_URL: ${{secrets.COIN_API_BASE_URL}}
          HD_COIN_API_KEY: ${{secrets.COIN_API_KEY}}
